name: Update Analogue Pocket openFPGA Library

run-name: ${{ github.actor }} is updating the Analogue Pocket openFPGA Library 🎮

on:
  pull_request:
    branches:
      - main
    paths:
      - '_data/sources.yml'
  schedule:
    # Run every 30 minutes
    - cron:  '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-inventory:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install Dependencies
        run: bundle install

      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.PR_CREATOR_APP_ID }}
          private_key: ${{ secrets.PR_CREATOR_PRIVATE_KEY }}

      - name: Setup .netrc
        uses: extractions/netrc@v2
        with:
          machine: api.github.com
          username: github-actions[bot]
          password: ${{ steps.generate-token.outputs.token }}

      - name: Updater - Update Cores
        run: |
          echo "⚙️ Updating openFPGA Library for Analogue Pocket..."
          ruby .github/workflows/updater/lib/updater.rb update-inventory
          echo "🎉 Successfully updated openFPGA library for Analogue Pocket!"

      - name: Updater - Generate Posts
        run: |
          echo "⚙️ Generating Jekyll Blog Posts..."
          ruby .github/workflows/updater/lib/updater.rb generate-posts
          echo "🎉 Successfully generated Blog Posts!"

      - name: Create Pull Request
        if: ${{ github.ref == 'refs/heads/main' }}
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          title: AUTOMATED PR FOR - Update openFPGA library for Analogue Pocket
          body: Update Analogue Pocket Cores Inventory
          token: ${{ steps.generate-token.outputs.token }}
          add-paths: |
            _data/cores/*.yml
            _data/platforms/*.yml
            _posts/*.md
            assets/images/**/*.png

      - name: Enable Auto-Merge & Approve PR
        if: steps.cpr.outputs.pull-request-number
        run: |
          gh pr merge --squash --auto "${{ steps.cpr.outputs.pull-request-number }}"
          gh pr review --approve "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
